apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-blog
  namespace: argocd
  labels:
    image-updater.argocd-image-updater.argoproj.io/managed: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/akash-pal/personal-blog
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
