apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-blog
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      app=ghcr.io/akash-pal/personal-blog
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[a-f0-9]{40}$
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/akash-pal/personal-blog
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: blog-frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
