apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-blog
  namespace: blog-frontend
  labels:
    app: personal-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-blog
  template:
    metadata:
      labels:
        app: personal-blog
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: personal-blog
          image: ghcr.io/akash-pal/personal-blog:c7e065f80d1cab44fc3a86492c50a16deb0471dd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
