apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-blog
  namespace: blog-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: personal-blog.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-blog
                port:
                  number: 80
